### register
POST http://localhost:4001/auth/register HTTP/1.1
content-type: application/x-www-form-urlencoded

username=username
&password=password

### register seller
POST http://localhost:4001/auth/register HTTP/1.1
content-type: application/x-www-form-urlencoded

username=username1
&password=password
&seller=true

### login
POST http://localhost:4001/auth/login HTTP/1.1
content-type: application/x-www-form-urlencoded

username=username
&password=password

### auth test
GET http://localhost:4001/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsInNlbGxlciI6dHJ1ZSwiaWF0IjoxNTU4OTY4MTk1LCJleHAiOjE1NTkwMTEzOTV9.r3hVhtD7E96d-CVi0Z4djy1FCDtCLOpfCgUOBwrKSao