### register
POST http://localhost:4001/api/auth/register HTTP/1.1
content-type: application/x-www-form-urlencoded

username=username
&password=password

### register seller
POST http://localhost:4001/api/auth/register HTTP/1.1
content-type: application/x-www-form-urlencoded

username=username1
&password=password
&seller=true

### login
POST http://localhost:4001/api/auth/login HTTP/1.1
content-type: application/x-www-form-urlencoded

username=orderSeller
&password=password

### upload file
POST http://localhost:4001/api/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9yZGVyU2VsbGVyIiwic2VsbGVyIjp0cnVlLCJpYXQiOjE1NTkyNzM0MzAsImV4cCI6MTU1OTMxNjYzMH0.j8mo_8dqGJAOQdui9Zw11ESouyJMz3hxTA_oP6fmW5w
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--